### ISSUE TITLE
Duplicate call to fuse_conv_batchnorm() in init()

### ISSUE THREAD

**Issue by philipp-schmidt** [stephanecharette/DarkHelp#1]
https://github.com/stephanecharette/DarkHelp/blob/c6b05ba2a93c004bda40c6ae8a6377c3340722cd/src-lib/DarkHelp.cpp#L145-L147

`load_network_custom` already does call `fuse_conv_batchnorm()` internally, this will call it twice.

**Comment by stephanecharette** [comment]
Thank you for the hint.  Removed duplicate call.
