### ISSUE TITLE
DarkHelp make Error

### ISSUE THREAD

**Issue by rsingh2083** [stephanecharette/DarkHelp#11]
(base) [anpr@ns build]$ make -j8
[ 25%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelp.cpp.o
[ 50%] Linking CXX static library libdarkhelp.a
[ 50%] Built target dh
[ 75%] Building CXX object src-tool/CMakeFiles/cli.dir/main.cpp.o
/home/anpr/DarkHelp/src-tool/main.cpp: In function ‘void show_help_window()’:
/home/anpr/DarkHelp/src-tool/main.cpp:205:25: error: loop variable ‘iter’ creates a copy from type ‘const std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >’ [-Werror=range-loop-construct]
  205 |         for (const auto iter : help)
      |                         ^~~~
/home/anpr/DarkHelp/src-tool/main.cpp:205:25: note: use reference type to prevent copying
  205 |         for (const auto iter : help)
      |                         ^~~~
      |                         &
cc1plus: all warnings being treated as errors
make[2]: *** [src-tool/CMakeFiles/cli.dir/build.make:76: src-tool/CMakeFiles/cli.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:160: src-tool/CMakeFiles/cli.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by stephanecharette** [comment]
Anything special you can tell me about your system?  Are you using a different compiler than what is usually installed?  What OS and what version are you on?  On Ubuntu 20.04, this is building correctly for me:
```
> make
[ 25%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelp.cpp.o
[ 50%] Linking CXX static library libdarkhelp.a
[ 50%] Built target dh
[ 75%] Building CXX object src-tool/CMakeFiles/cli.dir/main.cpp.o
[100%] Linking CXX executable DarkHelp
[100%] Built target cli
```
