### ISSUE TITLE
error Building DarkHelp (Windows)

### ISSUE THREAD

**Issue by sekisek** [stephanecharette/DarkHelp#12]
Building Darknet Commands all worked fine.
on the Building DarkHelp (Windows)  last command 

LINK : fatal error LNK1181: cannot open input file 'opencv_aruco.lib' [D:\AI\DarkSrc\darkhelp\build\src-tool\cli
       .vcxproj]

I uploaded a screenshot of the error ad of the file that's in the error

any ideas where this file is located or why do I get this?

![err](https://user-images.githubusercontent.com/29840960/132939117-848a2d55-e10d-4219-a0d0-5bd78aa40681.jpg)
![Screenshot 2021-09-10 233944](https://user-images.githubusercontent.com/29840960/132939118-a8a85291-8b81-4602-b590-b2cc3a7b6eb0.jpg)

**Comment by sekisek** [comment]
Hi,
I followed this guide a few days ago:
https://techzizou.com/yolo-installation-on-windows-and-linux/#install_windows

there were 3 options I choose the first one:

METHOD 1: Install OpenCV using Windows installer
Download OpenCV latest release Windows installer from https://opencv.org/releases/ .
Run the exe file, extract it to C drive and install it.
Lastly, give the following paths in the path environment variable for your System variables.

METHOD 2: Build OpenCV from source

METHOD 3: Build OpenCV from source with CUDA support to enable OpenCV-DNN-Cuda module

any suggestions?

**Comment by stephanecharette** [comment]
My suggestion is to follow the instructions on the DarkHelp github page.  See the readme for details.

**Comment by stephanecharette** [comment]
Specifically:  https://github.com/stephanecharette/DarkHelp#building-darknet-windows
Or:  https://github.com/stephanecharette/DarkHelp/blob/master/readme_windows.txt

**Comment by sekisek** [comment]
Got It to work! add to uninstall  opencv and build it again.
I am trying to install the DarkMark but I do to see any instructions for windows?

**Comment by stephanecharette** [comment]
DarkMark doesn't have Windows instructions.  Install it in a Virtualbox VM or in WSL2 in Windows 10.
