### ISSUE TITLE
Can I use DarkHelp along with YOLOV4? Can DarkHelp sends the output of YOLOv4 Darknet via tcp/ip?

### ISSUE THREAD

**Issue by PIjarihd** [stephanecharette/DarkHelp#16]
I have used YOLOv4 Darknet for object detection. I want to send the results of the Detection to C# gui via tcp/ip. Is it possible using DarkHelp? If yes, what procedures should I follow?
Thank You in Advance.

**Comment by stephanecharette** [comment]
DarkHelp is a C++ API wrapper for the original C Darknet API.  I'm not sure how that helps you with C# or TCP/IP.
