### ISSUE TITLE
Run on Python

### ISSUE THREAD

**Issue by arianyambao** [stephanecharette/DarkHelp#17]
Hi, this work is very great and I would just like to ask if there might be a possible where it can also be ran natively in Python in the future? Thank you so much.

**Comment by stephanecharette** [comment]
Nothing prevents it from running in Python.  The weights and config can be loaded using C, C++, Python, C#, etc.  Everything that supports YOLO.

**Comment by arianyambao** [comment]
Thank you so much for that response!
