### ISSUE TITLE
Compilation error on Raspberry Pi 4 / CM4 : cannot convert ‘const long long int*’ to ‘const time_t*’ {aka ‘const long int*’}

### ISSUE THREAD

**Issue by QuietLullaby** [stephanecharette/DarkHelp#19]
I stumbled on this compilation fatal error ([output.txt](https://github.com/stephanecharette/DarkHelp/files/7596157/output.txt)) while trying to compile Darkhelp on Compute Module 4 (armv7l Raspbian).
This error occurred in 2 files : first in [DarkHelpServer.cpp](https://github.com/stephanecharette/DarkHelp/blob/318e33d4fe7b97ec02e1086bac7c3adfd73ec74d/src-tool/DarkHelpServer.cpp) and secondly in [DarkHelpCli.cpp](https://github.com/stephanecharette/DarkHelp/blob/318e33d4fe7b97ec02e1086bac7c3adfd73ec74d/src-tool/DarkHelpCli.cpp)

I bypassed this error by editing line 230 in DarkHelpServer.cpp and line 1046 in DarkHelpCli.cpp https://github.com/stephanecharette/DarkHelp/blob/318e33d4fe7b97ec02e1086bac7c3adfd73ec74d/src-tool/DarkHelpServer.cpp#L230
https://github.com/stephanecharette/DarkHelp/blob/318e33d4fe7b97ec02e1086bac7c3adfd73ec74d/src-tool/DarkHelpCli.cpp#L1046

I wrote in both files: 

> std::time_t t = seconds;
> const auto lt = std::localtime(&t);

Can you check if my update is correct and update these two files if it complies with your code ?

Thank you in advance.

PS : Thank you for your job done on this project, it's incredible how it's easy to use darknet with your help.

**Comment by stephanecharette** [comment]
Thanks.  I made the change in the latest version.  Is this a 32-bit distro?

**Comment by QuietLullaby** [comment]
Nice, thank you !
Yes, it is a 32-bit distro !

**Comment by stephanecharette** [comment]
That explains the problem.  On my RPI 4 I'm running 64-bit Ubuntu, which is why I never saw this problem.

**Comment by QuietLullaby** [comment]
Ok, good to know !
You can mark this issue as resolved with your last commit if you want.
