### ISSUE TITLE
Error in make project

### ISSUE THREAD

**Issue by decesarojunior** [stephanecharette/DarkHelp#2]
I am trying to compile the project but has the following error occurred:

`[ 25%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelp.cpp.o
In file included from /opt/DarkHelp/src-lib/DarkHelp.cpp:6:0:
/opt/DarkHelp/src-lib/DarkHelp.hpp:559:7: error: âHersheyFontsâ in namespace âcvâ does not name a type
   cv::HersheyFonts annotation_font_face;
       ^~~~~~~~~~~~

/opt/DarkHelp/src-lib/DarkHelp.cpp: In member function âvirtual void DarkHelp::reset()â:
/opt/DarkHelp/src-lib/DarkHelp.cpp:201:2: error: âannotation_font_faceâ was not declared in this scope
  annotation_font_face    = cv::HersheyFonts::FONT_HERSHEY_SIMPLEX;
  ^~~~~~~~~~~~~~~~~~~~

/opt/DarkHelp/src-lib/DarkHelp.cpp:201:32: error: âcv::HersheyFontsâ has not been declared
  annotation_font_face    = cv::HersheyFonts::FONT_HERSHEY_SIMPLEX;
                                ^~~~~~~~~~~~

/opt/DarkHelp/src-lib/DarkHelp.cpp: In member function âvirtual DarkHelp::PredictionResults DarkHelp::predict_tile(cv::Mat, float)â:
/opt/DarkHelp/src-lib/DarkHelp.cpp:361:31: error: âcv::HersheyFontsâ has not been declared
      const auto font    = cv::HersheyFonts::FONT_HERSHEY_PLAIN;
                               ^~~~~~~~~~~~

/opt/DarkHelp/src-lib/DarkHelp.cpp:376:54: error: âFILLEDâ is not a member of âcvâ
      cv::rectangle(mat, label_rect, {255, 255, 255}, cv::FILLED, cv::LINE_AA);
                                                      ^~

/opt/DarkHelp/src-lib/DarkHelp.cpp:376:66: error: âLINE_AAâ is not a member of âcvâ
      cv::rectangle(mat, label_rect, {255, 255, 255}, cv::FILLED, cv::LINE_AA);
                                                                  ^~

/opt/DarkHelp/src-lib/DarkHelp.cpp: In member function âvirtual cv::Mat DarkHelp::annotate(float)â:
/opt/DarkHelp/src-lib/DarkHelp.cpp:565:58: error: âannotation_font_faceâ was not declared in this scope
    const cv::Size text_size = cv::getTextSize(pred.name, annotation_font_face, annotation_font_scale, annotation_font_thickness, &baseline);
                                                          ^~~~~~~~~~~~~~~~~~~~

/opt/DarkHelp/src-lib/DarkHelp.cpp:594:51: error: âannotation_font_faceâ was not declared in this scope
   const cv::Size text_size = cv::getTextSize(str, annotation_font_face, annotation_font_scale, annotation_font_thickness, nullptr);
                                                   ^~~~~~~~~~~~~~~~~~~~

/opt/DarkHelp/src-lib/DarkHelp.cpp:607:57: error: âannotation_font_faceâ was not declared in this scope
   const cv::Size text_size = cv::getTextSize(timestamp, annotation_font_face, annotation_font_scale, annotation_font_thickness, nullptr);
                                                         ^~~~~~~~~~~~~~~~~~~~

/opt/DarkHelp/src-lib/DarkHelp.cpp: In member function âvirtual std::__cxx11::string DarkHelp::duration_string()â:
/opt/DarkHelp/src-lib/DarkHelp.cpp:700:13: error: âsetwâ is not a member of âstdâ
   << "." << std::setw(3) << std::setfill('0')
             ^~~
/opt/DarkHelp/src-lib/DarkHelp.cpp:700:29: error: âsetfillâ is not a member of âstdâ
   << "." << std::setw(3) << std::setfill('0')
                             ^~~

src-lib/CMakeFiles/dh.dir/build.make:62: recipe for target 'src-lib/CMakeFiles/dh.dir/DarkHelp.cpp.o' failed
make[2]: *** [src-lib/CMakeFiles/dh.dir/DarkHelp.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src-lib/CMakeFiles/dh.dir/all' failed
make[1]: *** [src-lib/CMakeFiles/dh.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`
My libopencv-dev is 2.4.9.1

**Comment by decesarojunior** [comment]
Hello @stephanecharette, I removed Opencv 2.4.9 and installed 3.2.0 following the documentation at: 
https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html

But when executing make, there is an error when linking.  

`cd /opt/DarkHelp/build/src-tool && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cli.dir/link.txt --verbose=1
/usr/bin/c++  -O3 -DNDEBUG   CMakeFiles/cli.dir/main.cpp.o  -o DarkHelp  -L/usr/local/lib -Wl,-rpath,/usr/local/lib: ../src-lib/libdarkhelp.a -ldarknet /usr/local/lib/libopencv_stitching.so.3.2.0 /usr/local/lib/libopencv_superres.so.3.2.0 /usr/local/lib/libopencv_videostab.so.3.2.0 /usr/local/lib/libopencv_aruco.so.3.2.0 /usr/local/lib/libopencv_bgsegm.so.3.2.0 /usr/local/lib/libopencv_bioinspired.so.3.2.0 /usr/local/lib/libopencv_ccalib.so.3.2.0 /usr/local/lib/libopencv_dpm.so.3.2.0 /usr/local/lib/libopencv_freetype.so.3.2.0 /usr/local/lib/libopencv_fuzzy.so.3.2.0 /usr/local/lib/libopencv_hdf.so.3.2.0 /usr/local/lib/libopencv_line_descriptor.so.3.2.0 /usr/local/lib/libopencv_optflow.so.3.2.0 /usr/local/lib/libopencv_reg.so.3.2.0 /usr/local/lib/libopencv_saliency.so.3.2.0 /usr/local/lib/libopencv_stereo.so.3.2.0 /usr/local/lib/libopencv_structured_light.so.3.2.0 /usr/local/lib/libopencv_surface_matching.so.3.2.0 /usr/local/lib/libopencv_tracking.so.3.2.0 /usr/local/lib/libopencv_xfeatures2d.so.3.2.0 /usr/local/lib/libopencv_ximgproc.so.3.2.0 /usr/local/lib/libopencv_xobjdetect.so.3.2.0 /usr/local/lib/libopencv_xphoto.so.3.2.0 /usr/lib/x86_64-linux-gnu/libmagic.so -lstdc++fs -lpthread /usr/local/lib/libopencv_shape.so.3.2.0 /usr/local/lib/libopencv_viz.so.3.2.0 /usr/local/lib/libopencv_phase_unwrapping.so.3.2.0 /usr/local/lib/libopencv_rgbd.so.3.2.0 /usr/local/lib/libopencv_calib3d.so.3.2.0 /usr/local/lib/libopencv_video.so.3.2.0 /usr/local/lib/libopencv_datasets.so.3.2.0 /usr/local/lib/libopencv_dnn.so.3.2.0 /usr/local/lib/libopencv_face.so.3.2.0 /usr/local/lib/libopencv_plot.so.3.2.0 /usr/local/lib/libopencv_text.so.3.2.0 /usr/local/lib/libopencv_features2d.so.3.2.0 /usr/local/lib/libopencv_flann.so.3.2.0 /usr/local/lib/libopencv_objdetect.so.3.2.0 /usr/local/lib/libopencv_ml.so.3.2.0 /usr/local/lib/libopencv_highgui.so.3.2.0 /usr/local/lib/libopencv_photo.so.3.2.0 /usr/local/lib/libopencv_videoio.so.3.2.0 /usr/local/lib/libopencv_imgcodecs.so.3.2.0 /usr/local/lib/libopencv_imgproc.so.3.2.0 /usr/local/lib/libopencv_core.so.3.2.0
/usr/bin/ld: warning: libopencv_calib3d.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_contrib.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_core.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_features2d.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_flann.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_gpu.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_highgui.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_imgproc.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_legacy.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_ml.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_objdetect.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_ocl.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_photo.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_stitching.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_superres.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_ts.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_video.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_videostab.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libdarknet.so: undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::imencode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
/usr/local/lib/libdarknet.so: undefined reference to `vtable for cv::_InputArray'
/usr/local/lib/libdarknet.so: undefined reference to `cv::createTrackbar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*, int, void (*)(int, void*), void*)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::getTextSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double, int, int*)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::namedWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat const&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::circle(cv::Mat&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::rectangle(cv::Mat&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::VideoWriter::VideoWriter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double, cv::Size_<int>, bool)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::randn(cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::merge(std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::_OutputArray const&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::VideoCapture::VideoCapture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::resizeWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::putText(cv::Mat&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::_InputArray::_InputArray(double const&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::line(cv::Mat&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::split(cv::Mat const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::setWindowProperty(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::moveWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::setMouseCallback(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (*)(int, int, int, int, void*), void*)'
/usr/local/lib/libdarknet.so: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
src-tool/CMakeFiles/cli.dir/build.make:141: recipe for target 'src-tool/DarkHelp' failed
make[2]: *** [src-tool/DarkHelp] Error 1
make[2]: Leaving directory '/opt/DarkHelp/build'
CMakeFiles/Makefile2:140: recipe for target 'src-tool/CMakeFiles/cli.dir/all' failed
make[1]: *** [src-tool/CMakeFiles/cli.dir/all] Error 2
make[1]: Leaving directory '/opt/DarkHelp/build'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by stephanecharette** [comment]
You still haven't answered my questions.  What OS are you using?  Why are you not using the normal command to install OpenCV?  Why are you using such an old versions of OpenCV?

Obviously you still have problems because your error messages reference OpenCV 2.4 as well as 3.2.  For example:

```
/usr/local/lib/libopencv_highgui.so.3.2.0 /usr/local/lib/libopencv_photo.so.3.2.0 /usr/local/lib/libopencv_videoio.so.3.2.0 /usr/local/lib/libopencv_imgcodecs.so.3.2.0 /usr/local/lib/libopencv_imgproc.so.3.2.0 /usr/local/lib/libopencv_core.so.3.2.0
/usr/bin/ld: warning: libopencv_calib3d.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_contrib.so.2.4, needed by /usr/local/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
```

You need to sort out your use of libraries, and you need to make sure things are installed correctly and built correctly.

**Comment by decesarojunior** [comment]
@stephanecharette, My OS is a Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux.

Initially I did apt-get install libopencv-dev which installed version 2.4.9. Then the compilation of the darknet worked. But when I compiled darkHelp make did not find any references to opencv. So I decided to remove 2.4.9 and install opencv 3.2.0 from the sources. Now, when compiling darknet and darkHelp again, referencing libs 2.4.

I have already removed all libs from version 2.4.

**Comment by stephanecharette** [comment]
> I have already removed all libs from version 2.4.

Since things are still referencing v2.4, obviously not everything has been removed.

**Comment by stephanecharette** [comment]
> @stephanecharette, My OS is a Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux.

Doing a quick Google search, the current version of Debian is v10 (Buster), or v11 (Bullseye).  But you're on v4 (Etch)?  Isn't that ancient?  Looking it up, Etch is from 2007.  You cannot expect modern software to work on such ancient distros.

I typically make sure DarkHelp and DarkMark works on Ubuntu 20.04 and 18.04 (2020, 2018) and every once in a while I'll boot up an old version of 16.04 from 2016.  But going back to 2007 is too old.

**Comment by shikhab25** [comment]
Hi there @stephanecharette.
I faced problem during "make -j16" for darkhelp.
I am using 
ubuntu vm 20.04 lts
opencv 4.2

![Screenshot from 2021-04-18 21-13-03](https://user-images.githubusercontent.com/82793498/115180627-eef69300-a08a-11eb-9dee-e3c36a1e9d83.png)

Thank you in advance.

**Comment by stephanecharette** [comment]
You need to follow the build steps.

**Comment by stephanecharette** [comment]
I suggest you re-do the steps exactly as described in the readme.  Because it explains exactly how to build and install all parts, including `darknet.h`.  This is also described and shown in the tutorial video in youtube:  https://www.youtube.com/watch?v=pJ2iyf_E9PM

**Comment by shikhab25** [comment]
@stephanecharette ,
unlike video, i set AVX =0 in make file. Only then, I was able to proceed without error. 

Thanks for your quick reply.

**Comment by stephanecharette** [comment]
Can this be closed?
