### ISSUE TITLE
How can I install DarkHelp if I have installed Darknet using Cmake?

### ISSUE THREAD

**Issue by blackShine-2** [stephanecharette/DarkHelp#23]
I have installed Darknet already using Cmake. Now, how should I install and use DarkHelp?

**Comment by stephanecharette** [comment]
By following the instructions:  https://github.com/stephanecharette/DarkHelp#how-to-build-darkhelp-linux

**Comment by blackShine-2** [comment]
> By following the instructions: https://github.com/stephanecharette/DarkHelp#how-to-build-darkhelp-linux

Actually I have already installed darknet using [Cmake ](https://cmake.org/)in windows 10. [This instruction](https://github.com/stephanecharette/DarkHelp#building-darkhelp-windows) is helpful using vcpkg. So, how should I do now? or should I install darknet again using vcpkg?

**Comment by stephanecharette** [comment]
Your call.  Many different ways to do it.  If you are using Windows, then use one of the many Windows instructions, including the one you linked.
