### ISSUE TITLE
CMAKE build issue Windows Server: Cant find FindCUDNN.cmake CUDNNconfig.cmake CUDNN_config.cmake

### ISSUE THREAD

**Issue by SummerPAI** [stephanecharette/DarkHelp#28]
Trying to install DarkHelp on Windows Server 2019 with GeForce Ge 1660. Have installed OpenCV with DNN , Installed DarkNet as per the Darknet instructions.
All Path variables have been updated ,including for CUDNN and CUDNN_PATH and server restarted. 
OpenCV was built from source with DNN. 
Darknet is running correctly from the CLI 

Now trying to install DarkHelp as per the  sequence in readme_windows.txt.

When running:
cmake -DCMAKE_BUILD_TYPE=Release - DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake ..

using the command as above as well as when replicating via CMAKE GUI I get the following  error:

CMake Error at C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:829 (_find_package):
  By not providing "FindCUDNN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CUDNN", but
  CMake did not find one.

  Could not find a package configuration file provided by "CUDNN" with any of
  the following names:

    CUDNNConfig.cmake
    cudnn-config.cmake

  Add the installation prefix of "CUDNN" to CMAKE_PREFIX_PATH or set
  "CUDNN_DIR" to a directory containing one of the above files.  If "CUDNN"
  provides a separate development package or SDK, be sure it has been
  installed.

I located the FindCUDNN.cmake file is in several directories: Opencv/cmake darknet/share/, darknet/cmake/modules, vcpkg/ports/
Any idea how to update the configuration to point towards the correct file?
Thanks in advance

**Comment by stephanecharette** [comment]
Sorry, I'm not familiar with building on Windows.  I have no idea how to get cmake to find CUDNN.

I'd start with a google search.  Or stackoverflow, like this one:  https://stackoverflow.com/questions/61533880/how-to-find-cudnn-with-cmake

**Comment by SummerPAI** [comment]
Resolved by installing and running all on linux box....
