### ISSUE TITLE
yolov7 

### ISSUE THREAD

**Issue by MyraBaba** [stephanecharette/DarkHelp#29]
Hi, @stephanecharette 

I am new to darknet and impressed by your c++ DarkHelp very good coverage. 

We are using AI for detecting vehicles from intersections . currently using yolov7 and fairy good enough . We want to give a shot and possibly change to c++ . can we use yolov7 models with darknet. ? If now which model you suggest for replacing yolov7e6 ?

We also want to detect small vehicles from 4Mp resolution . tiling looks very good solution for that.  detecting and tracking (bytetrack at the moment)

When tiling we are inferencing more than one image per image. so it make slower . However can we  doing inference simultaneously (batch) for tiled version ?

**Comment by stephanecharette** [comment]
I'm only familiar with YOLO up to v4.  I've not yet made the move to v7.

Darknet's support for batch inference is not complete.  I've not added support for it yet in DarkHelp.

**Comment by stephanecharette** [comment]
For anyone else looking to use YOLOv7, note that it does work with DarkHelp.  I have a video of it here, comparing YOLOv4-tiny and YOLOv7-tiny:  https://www.youtube.com/watch?v=JSgDs0XXz8M
