### ISSUE TITLE
DarkHelp Compile error mac os x

### ISSUE THREAD

**Issue by MyraBaba** [stephanecharette/DarkHelp#30]
Hi I have below strange error when compiling darknet.

> cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building ver: 1.4.27-1
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenCV: /usr/local (found version "3.4.8")
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Magic
    linked by target "cli" in directory /Users/tulpar/Project/DarkHelp/src-tool
    linked by target "server" in directory /Users/tulpar/Project/DarkHelp/src-tool

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
╭─tulpar@tulpar.local ~/Project/DarkHelp/build  ‹master›
╰─➤  make -j4                                                                                                                                       1 ↵
[ 44%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelpNN.cpp.o
[ 44%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelpUtils.cpp.o
[ 44%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelpConfig.cpp.o
[ 44%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelpPredictionResult.cpp.o
/Users/tulpar/Project/DarkHelp/src-lib/DarkHelpNN.cpp:821:23: error: unused function 'convert_darknet_image_to_opencv_mat' [-Werror,-Wunused-function]
static inline cv::Mat convert_darknet_image_to_opencv_mat(const image img)
                      ^
1 error generated.
make[2]: *** [src-lib/CMakeFiles/dh.dir/DarkHelpNN.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src-lib/CMakeFiles/dh.dir/all] Error 2
make: *** [all] Error 2

**Comment by stephanecharette** [comment]
> > CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> > Please set them or make sure they are set and tested correctly in the CMake files:
> > Magic

Install libmagic.  Or, you'll have to modify the code to use the same codepath as Windows to get around it not being installed.

> [ 44%] Building CXX object src-lib/CMakeFiles/dh.dir/DarkHelpPredictionResult.cpp.o
> /Users/tulpar/Project/DarkHelp/src-lib/DarkHelpNN.cpp:821:23:
> error: unused function 'convert_darknet_image_to_opencv_mat' [-Werror,-Wunused-function]
> static inline cv::Mat convert_darknet_image_to_opencv_mat(const image img) ^ 1 error generated.

Having an unused function in a library is not an error.  If your compiler/linker doesn't allow it, then get rid of the `Werror` flag, or negate the `-Wunused-function` one.
