### ISSUE TITLE
cannot open source file "DarkHelp.hpp"

### ISSUE THREAD

**Issue by nithrous** [stephanecharette/DarkHelp#32]
I did all steps from readme_windows.txt, generated a Visual Studio solution, but when I build it I see this:

`cannot open source file "DarkHelp.hpp" D:\Projects\DarkHelp\src-lib\DarkHelpConfig.cpp`

![image](https://user-images.githubusercontent.com/10476019/195216256-66d6f0be-983b-4816-b9df-0b9d0ae49162.png)

How to fix it?

**Comment by stephanecharette** [comment]
Did you delete it?

**Comment by stephanecharette** [comment]
File is there:  https://github.com/stephanecharette/DarkHelp/tree/master/src-lib

**Comment by nithrous** [comment]
I just followed the instructions. Is there any way to make it work?

**Comment by stephanecharette** [comment]
Yes, it works for everyone else, including me.  I would say you need to carefully follow the instructions.  If you don't have that file, then my next question would be:  why did you delete it?  And if you don't have it, then I would clone the repo and start over cause you did something wrong.
