### ISSUE TITLE
DarkHelp Crashes when using Single Channel Networks and OpenCV

### ISSUE THREAD

**Issue by erikstauber** [stephanecharette/DarkHelp#33]
When using DarkHelp to load a yolov4-tiny single channel network (grayscale images), and configuring it to use OPENCV as a backend, the program crashes.  This can fixed be setting the initial dummy matrix sent to the OpenCV constructor with the appropriate matrix type of CV_8UC1, as shown:

![image](https://user-images.githubusercontent.com/36085655/208718419-07a04b39-69b7-4d8a-8611-48fc8a8d6afe.png)

Rather than hardcoding, I think it would be best to read the darknet .cfg file to get the number of channels in the network, and use that value to set the matrix type appropriately, similar to what is done immediately above this section of code with regards to the network dimensions.

Both DarkMark and DarkHelp are excellent!

**Comment by stephanecharette** [comment]
Sorry about that.  Good catch.  I will try to get that fixed tonight.

**Comment by stephanecharette** [comment]
Please do a git pull and see if the most recent version fixes this issue for you.  I don't have a single-channel network trained, so I cannot fully test the changes I've made.

**Comment by erikstauber** [comment]
It works!

Thanks.
