### ISSUE TITLE
Hide label in annotation

### ISSUE THREAD

**Issue by dinhtuanan** [stephanecharette/DarkHelp#43]
Hi,

I use DarkHelp version: 1.4.15-1. 
The commit is : https://github.com/stephanecharette/DarkHelp/commit/2c0fdbb35d7be89533e9976cf83196b9bc76b0ef

I want image detection results without labels and percentages. I read Darkhelp's parameters to do that (https://www.ccoderun.ca/darkhelp/api/Parameters.html). I see there are 2 parameters -o and -p. When I use them, only the -p parameter works. I read that auto hide label available since 2020-07-03 (https://www.ccoderun.ca/darkhelp/api/classDarkHelp_1_1Config.html#a3086f69df165e7be96cd909682b44c54)

This is my command:
```
Darkhelp config_path weight_path names_path -f 2 --threshold 0.5 -k -l /opt/image_list.txt --outdir /opt/results -Y jpg -j -o true -p false >/opt/abc.log
```

I also tried –autohide instead of -o . Tried all the true,false,on,off,1,0 but they don't work

![image](https://github.com/stephanecharette/DarkHelp/assets/108641003/e0956483-5d27-416c-b3e7-55903eb92add)

You can see that percentage is disappear but the label still there. 

I wonder if I am using it incorrectly? Is there any way to hide the label?

Regards,
An

**Comment by stephanecharette** [comment]
When you use the DarkHelp API, set the `suppress_all_labels` flag to `true`:  https://www.ccoderun.ca/darkhelp/api/classDarkHelp_1_1Config.html#a80ab823f043d6f14f90b20c21fafb3b0

Autohide only hides the label if the label is bigger than the box.  See examples here:  https://www.ccoderun.ca/darkhelp/api/classDarkHelp_1_1Config.html#a3086f69df165e7be96cd909682b44c54

I just tried, and both `-o` and `-p` are working perfectly.  Not sure why you say it doesn't work.

The option I think you want is described here in the CLI.  When you run `DarkHelp --help` you should see this:

```
...
     0.01-1.0+. Default is 0.25.

   --suppress
     Suppress all labels (bounding boxes are shown, but not the labels at
     the top of each bounding box).

   --redirection <true|false|on|off|yes|no|t|f|y|n|1|0>
...
```

**Comment by dinhtuanan** [comment]
It seems my darkhelp is quite old so it doesn't have that flag
![image](https://github.com/stephanecharette/DarkHelp/assets/108641003/8b10e34b-ad53-47ab-b954-76dfb37f3cb4)

**Comment by dinhtuanan** [comment]
Thank you so much. I will close the issue
