### ISSUE TITLE
Linker errors on Windows

### ISSUE THREAD

**Issue by Foxsterc** [stephanecharette/DarkHelp#44]
Hi

Getting this error when building on Windows.

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Darknet
    linked by target "dh" in directory F:/src/DarkHelp/src-lib
    linked by target "cli" in directory F:/src/DarkHelp/src-tool
    linked by target "combine" in directory F:/src/DarkHelp/src-tool
    linked by target "server" in directory F:/src/DarkHelp/src-tool
    linked by target "display_single_image" in directory F:/src/DarkHelp/src-apps
    linked by target "process_video_webcam" in directory F:/src/DarkHelp/src-apps
    linked by target "display_single_image_custom_settings" in directory F:/src/DarkHelp/src-apps
    linked by target "display_single_image_snapping" in directory F:/src/DarkHelp/src-apps
    linked by target "display_using_bundle" in directory F:/src/DarkHelp/src-apps
    linked by target "video_display_realtime" in directory F:/src/DarkHelp/src-apps
    linked by target "process_many_images_on_threads" in directory F:/src/DarkHelp/src-apps
    linked by target "process_single_image" in directory F:/src/DarkHelp/src-apps
    linked by target "process_using_bundle_and_dhthreads" in directory F:/src/DarkHelp/src-apps
    linked by target "rotate_images" in directory F:/src/DarkHelp/src-apps
    linked by target "save_webcam_to_video" in directory F:/src/DarkHelp/src-apps
    linked by target "using_c_api" in directory F:/src/DarkHelp/src-apps
    linked by target "video_object_counter" in directory F:/src/DarkHelp/src-apps
    linked by target "DarkHelp_cam" in directory F:/src/DarkHelp/src-cam
`

Building in Visual Studio gives

<img width="1369" alt="image" src="https://github.com/stephanecharette/DarkHelp/assets/13538417/344a203c-bcce-46d6-9950-d59eb77d7834">

darkhelp.lib doesn't exist.

Thanks,

**Comment by stephanecharette** [comment]
Please carefully read the build instructions where this is addressed.

**Comment by Foxsterc** [comment]
Ah yes! I missed this line.

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake -DDarknet="C:/Program Files/Darknet/lib/darknet.lib" ..`
