### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by huniz86** [stephanecharette/DarkHelp#47]
Build failed.

"C:\src\DarkHelp\build\DarkHelp.sln" (Build target) (1) ->
"C:\src\DarkHelp\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\src\DarkHelp\build\src-cam\DarkHelp_cam.vcxproj.metaproj" (default target) (3) ->
"C:\src\DarkHelp\build\src-lib\dh.vcxproj.metaproj" (default target) (4) ->
"C:\src\DarkHelp\build\src-lib\dh.vcxproj" (default target) (23) ->
(ClCompile target) ->
C:\src\DarkHelp\src-lib\DarkHelpNN.cpp(1619,22): error C2039: 'create_yolo_heatmaps': not a member of 'Darknet' [C:\src\DarkHelp\build\src-lib\dh.vcxproj]
C:\src\DarkHelp\src-lib\DarkHelpNN.cpp(1619,22): error C3861: 'create_yolo_heatmaps': identifier not found [C:\src\DarkHelp\build\src-lib\dh.vcxproj]
C:\src\DarkHelp\src-lib\DarkHelpNN.cpp(1636,17): error C2039: 'create_yolo_heatmaps': not a member of 'Darknet' [C:\src\DarkHelp\build\src-lib\dh.vcxproj]
C:\src\DarkHelp\src-lib\DarkHelpNN.cpp(1636,17): error C3861: 'create_yolo_heatmaps': identifier not found [C:\src\DarkHelp\build\src-lib\dh.vcxproj]
C:\src\DarkHelp\src-lib\DarkHelpNN.cpp(1636,3): error C2593: 'operator =' is ambiguous [C:\src\DarkHelp\build\src-lib\dh.vcxproj]

0 warnings

5 errors

**Comment by stephanecharette** [comment]
My guess is you're using an old version of Darknet/YOLO which doesn't support heatmaps.  Please run `darknet --version` and post the version you are using.

**Comment by huniz86** [comment]
> My guess is you're using an old version of Darknet/YOLO which doesn't support heatmaps. Please run `darknet --version` and post the version you are using.

C:\Program Files\Darknet\bin>darknet --version
Darknet V3 "Jazz" v3.0-174-ga1e62b61
CUDA runtime version 12060 (v12.6), driver version 12070 (v12.7)
cuDNN version 12060 (v9.6.0), use of half-size floats is ENABLED
=> 0: NVIDIA GeForce RTX 3090 [#8.6], 24.0 GiB
OpenCV v4.10.0, Windows 11 Pro

**Comment by stephanecharette** [comment]
I made a mistake the other day.  Everything is working correctly as far as I can tell:

![image](https://github.com/user-attachments/assets/881b9940-1c0e-49e3-996e-9a1cfd53317c)

From your post, you are running v3.0-174 from Oct 31.  This is _prior_ to support for heatmaps, which was added in November and December.  Please make sure you are using the most recent version of both Darknet and DarkHelp.

**Comment by stephanecharette** [comment]
@huniz86 Any update?  Can this be closed?

**Comment by huniz86** [comment]
> @huniz86 Any update? Can this be closed?

Sorry for the late reply.
This issue has been resolved, so I will close it.
Thank you.
