### ISSUE TITLE
Implement tkDNN?

### ISSUE THREAD

**Issue by grandprixgp** [stephanecharette/DarkHelp#5]
Do you believe it would be viable to implement tkDNN into DarkHelp as an option?

**Comment by stephanecharette** [comment]
I'd never heard of tkDNN until I googled it just now, so it is highly unlikely I will be implementing support for it unless someone was willing to sponsor the project.

**Comment by grandprixgp** [comment]
It is quite a big task, but I figured it was worth asking. We have 4 sponsors now, so if anyone else sees this and is interested in a tkDNN wrapper in the style of DarkHelp, hop on board :)
