### ISSUE TITLE
JSON exporting available?

### ISSUE THREAD

**Issue by jyothir07** [stephanecharette/DarkHelp#7]
Is there any option to export the detections as JSON file as in darknet output exporting. The results are printed on the command prompt.

**Comment by stephanecharette** [comment]
Please see the online docs, or run with `--help`:  https://www.ccoderun.ca/darkhelp/api/ShellScripting.html

**Comment by jyothir07** [comment]
> Please see the online docs, or run with `--help`: https://www.ccoderun.ca/darkhelp/api/ShellScripting.html

Thanks. Got it .
