### ISSUE TITLE
Does DarkHelp Implement Image Tiling during Inference?

### ISSUE THREAD

**Issue by seabass1217** [stephanecharette/DarkHelp#9]
@stephanecharette I'm exploring image tiling to improve small object detection.  I see that DarkHelp and Darkmark has the ability implement image tiling on datasets; but it's not clear to me if Darkmark implements tiling during inference.

Thanks in advance,

**Comment by stephanecharette** [comment]
See:  https://www.ccoderun.ca/darkmark/Summary.html#DarkMarkSettings

**Comment by stephanecharette** [comment]
![image](https://user-images.githubusercontent.com/5061352/127739170-a21bf368-2a87-496b-a0ab-7a1da5571c35.png)

Also see the letter `t`:  https://www.ccoderun.ca/darkmark/Keyboard.html

**Comment by stephanecharette** [comment]
But why are you posting an issue on the DarkHelp project asking whether DarkMark supports something?

**Comment by seabass1217** [comment]
@stephanecharette, 
Thanks!  I'm still figuring out the differences between the tools.
